### ISSUE TITLE
Can not load "webpack" error

### ISSUE THREAD

**Issue by arshtepe** [webpack-contrib/karma-webpack#220]
## **BEFORE YOU SUBMIT** please read the following:

**I'm submitting a bug report**

**Webpack version:**
2.2.1

**Webpack Karma version**:
2.0.2

**Karma version**:
1.4.1

**Please tell us about your environment:**
Linux

**Browser:** [Phantom XX | Chrome XX | Firefox XX | IE XX | Safari XX | Other XX] << (All)

**Current behavior:**
```
ERROR [preprocess]: Can not load "webpack"!
  Error
    at webpack (...node_modules/webpack/lib/webpack.js:19:9)
    at new Plugin (.../node_modules/karma-webpack/lib/karma-webpack.js:65:18)
    at invoke (.../node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (.../node_modules/di/lib/injector.js:59:20)
    at get (.../node_modules/di/lib/injector.js:48:43)
    at .../node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (.../node_modules/di/lib/injector.js:70:31)
    at Injector.get (.../node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (.../node_modules/karma/lib/preprocessor.js:55:20)
    at Array.forEach (native)
    at createPreprocessor (.../node_modules/karma/lib/preprocessor.js:74:20)
    at Array.invoke .../node_modules/di/lib/injector.js:75:15)
    at get (.../node_modules/di/lib/injector.js:48:43)
    at .../node_modules/di/lib/injector.js:71:14
    at Array.map (native)
```

**Expected/desired behavior:**
Tests must work :) 

karma config 
```js
module.exports = (basePath, files, webpackConfig) => {
    var logLevel = 'LOG_INFO';
    var browsers = ["PhantomJS"];
    var singleRun = true;
    let entryName;
    if(argv.entry) {
        entryName = `**/${argv.entry.replace(/\.js$/, "")}.js`
    }
    let entryPath = argv.entryPath;
    let searchPattern = entryName || entryPath || '**/*.js';
    let preprocessors = {};

    if(Array.isArray(!files)) {
        files = [];
    }

    preprocessors[searchPattern] = ['webpack', 'sourcemap'];
    files.push(searchPattern); //test must be last include file

    if (argv.debug) {
        logLevel = 'LOG_DEBUG';
    }

    if (argv.gui) {
        singleRun = false;
        browsers = ["Chrome"];
    }

    return {
        frameworks: ['jasmine'],
        basePath: basePath,
        browsers: browsers,
        files: files,
        colors: true,
        singleRun: singleRun,
        preprocessors: preprocessors,
        webpack: webpackConfig,
        logLevel: logLevel,
        plugins: [
            require("karma-jasmine"),
            require("karma-sourcemap-loader"),
            require("karma-webpack"),
            require("karma-phantomjs-launcher"),
            require("karma-chrome-launcher"),
            require("karma-sourcemap-loader")
        ]
    }
};
```

**Comment by arshtepe** [comment]
Problem was in invalid config, but karma doesn`t show stacktrace with error, only message " Can not load "webpack"!"

**Comment by arshtepe** [comment]
karma not pass entry to webpack config. It had worked earlier .
```js
preprocessors[searchPattern] = ['webpack', 'sourcemap'];
```

**Comment by arshtepe** [comment]
Entry in webpack config can not be empty object.
