### ISSUE TITLE
Webpack errors are not logged

### ISSUE THREAD

**Issue by patope** [webpack-contrib/karma-webpack#227]
**I'm submitting a feature request**

**Webpack version:**
2.x

**Webpack Karma version**:
2.0.x

**Karma version**:
1.x

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
karma-webpack do not log webpack configuration issues. Simply reports
```
26 02 2017 22:08:57.640:ERROR [preprocess]: Can not load "webpack"!
  Error
    at webpack (..../node_modules/webpack/lib/webpack.js:19:9)
```
code here https://github.com/webpack-contrib/karma-webpack/blob/v2/src/karma-webpack.js#L65

**Expected/desired behavior:**
Instead karma-webpack should catch expcetion thrown by webpack and log message on exception.

Replacing above line with 
```
  var compiler;
  try {
    compiler = webpack(webpackOptions);
  } catch(e) {
    console.error(e.message);
    throw e;
  }
```
Report is
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'preLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   Options affecting the normal modules (`NormalModuleFactory`).
 - configuration.resolve.extensions[0] should not be empty.
26 02 2017 22:08:57.640:ERROR [preprocess]: Can not load "webpack"!
  Error
    at webpack (..../webpack/lib/webpack.js:19:9)
```

* **What is the motivation / use case for changing the behavior?**
Make easier to resolve webpack configuration issues.

**Comment by d3viant0ne** [comment]
That's not an error, that is a malformed configuration.

Everything you need to resolve the issues with your configuration are in the stack you pasted in.

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'preLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   Options affecting the normal modules (`NormalModuleFactory`).
 - configuration.resolve.extensions[0] should not be empty.
```

**Comment by patope** [comment]
@d3viant0ne yes, i know. But, that is not point of this report. Could you reread this?

karma-webpack currently keeps this information hidden from user and reports only `Can not load "webpack"!`. Which is not very informative and generates unneccessary support requests for you.

**Comment by d3viant0ne** [comment]
@patope - Yeah, I misread the first part. I'll have this fixed and out to npm shortly.

**Comment by marcusellis05** [comment]
Do you have an ETA on the fix?

**Comment by d3viant0ne** [comment]
@marcusellis05 - It's next on my list after css-loader to go out. Couple of hours to npm

**Comment by chrisrwilkes** [comment]
I am getting this error only when running `npm test`. Normal `webpack` works fine:

```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   -> The entry point(s) of the compilation.
   Details:
    * configuration.entry should not be empty.
      -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
    * configuration.entry should be a string.
      -> An entry point without name. The string is resolved to a module which is loaded upon startup.
    * configuration.entry should be an array:
      [non-empty string]
    * configuration.entry should be an instance of function
      -> A Function returning an entry object, an entry string, an entry array or a promise to these things.
    at webpack (C:\l\node_modules\webpack\lib\webpack.js:19:9)
    at new Plugin (C:\node_modules\karma-webpack\lib\karma-webpack.js:69:16)
```

**Comment by chrisrwilkes** [comment]
let me know if I should open a new thread
