### ISSUE TITLE
Error: not a directory at MemoryFileSystem.mkdirpSync

### ISSUE THREAD

**Issue by mischkl** [webpack-contrib/karma-webpack#231]
**I'm submitting a bug report**
(possibly related: #174, #230)

**Webpack version:**
2.2.1

**Webpack Karma version**:
2.0.2

**Karma version**:
1.5.0

**Typescript version**:
2.1.6

**awesome-typescript-loader version**:
3.0.8

**Please tell us about your environment:**
Windows 7

**Browser:**
PhantomJS 2.1.13

**Current behavior:**

When attempting to run Karma tests, I get the following error message, after Webpack init (`[at-loader] Ok` shows up from the awesome-typescript-loader) but before any tests start running:
```bash
[at-loader] Using typescript@2.1.6 from typescript and "tsconfig.json" from C:\workspace\ecm-awf-frontend\tsconfig.json.

[at-loader] Checking started in a separate process...

[at-loader] Ok, 2.207 sec.

[at-loader] Checking started in a separate process...

[at-loader] Ok, 1.17 sec.
Error: not a directory
    at MemoryFileSystem.mkdirpSync (C:\workspace\ecm-awf-frontend\node_modules\memory-fs\lib\MemoryFileSystem.js:144:10)
    at MemoryFileSystem.(anonymous function) [as mkdirp] (C:\workspace\ecm-awf-frontend\node_modules\memory-fs\lib\MemoryFileSystem.js:279:34)
    at Compiler.<anonymous> (C:\workspace\ecm-awf-frontend\node_modules\webpack\lib\Compiler.js:311:27)
    at C:\workspace\ecm-awf-frontend\node_modules\async\dist\async.js:3025:16
    at eachOfArrayLike (C:\workspace\ecm-awf-frontend\node_modules\async\dist\async.js:940:9)
    at eachOf (C:\workspace\ecm-awf-frontend\node_modules\async\dist\async.js:990:5)
    at Object.eachLimit (C:\workspace\ecm-awf-frontend\node_modules\async\dist\async.js:3089:3)
    at Compiler.emitFiles (C:\workspace\ecm-awf-frontend\node_modules\webpack\lib\Compiler.js:301:20)
    at Immediate.<anonymous> (C:\workspace\ecm-awf-frontend\node_modules\memory-fs\lib\MemoryFileSystem.js:288:4)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Expected/desired behavior:**

Karma tests start running normally.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

Here is a gist of my config files for webpack and karma (reduced to the essential parts that I think could be relevant):
https://gist.github.com/mischkl/a7a1db5c5e89da0e5ffd536d81a42283

I'm getting this issue after upgrading to webpack 2.2.1, karma 1.5.0 and karma-webpack 2.0.2, including migrating to the new Webpack 2 API that uses 'rules' instead of 'loaders', etc. All my other webpack builds are essentially the same and seem to work hunky-dory. Could it be that there is an incompatibility here with the new syntax of the new Webpack config file format?

**Comment by mischkl** [comment]
OK, it seems that the problem was that I needed to eliminate the "entry" property of my webpack config. In my case that meant adding the second line below:

```js
var webpackConfig = require('./webpack.test.config');
webpackConfig.entry = null;
```

Hope this helps someone else.

**Comment by alphapilgrim** [comment]
I have the same problem. Using the latest versions. Just not using any .ts. [GIST](https://gist.github.com/alphapilgrim/4307730fa9454aaa8b0b141415ba5b2d)

**Comment by mgwidmann** [comment]
Anyone know what version this started from? Would be nice to see a workaround until the issue is resolved...

**Comment by mgwidmann** [comment]
I was able to fix this by properly setting `basePath` in my `karma.config.js` file like so:

```
config.set({
  basePath: path.resolve(path.join(__dirname, '..')),
  ...
```
