### ISSUE TITLE
TypeError: Path must be a string

### ISSUE THREAD

**Issue by Pwntastic** [webpack-contrib/karma-webpack#286]
**I'm submitting a bug report**

**Webpack version:**
3.10.0

**Webpack Karma version**:
2.0.9

**Karma version**:
1.7.1

**Please tell us about your environment:**
OSX 10.12.6

**Browser:** [Phantom XX | Chrome XX | Firefox XX | IE XX | Safari XX | Other XX]
Phantom | Chrome 64

**Current behavior:**
Karma fails to run, throwing a TypeError

**Expected/desired behavior:**
Karma runs without errors

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

Use karma-webpack 2.0.8-2.0.9 and a TypeError will be thrown:

```
TypeError: Path must be a string. Received 0
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at /Users/jared.nyman/project/node_modules/karma-webpack/lib/karma-webpack.js:203:45
    at /Users/jared.nyman/project/node_modules/karma-webpack/node_modules/async/lib/async.js:246:17
    at /Users/jared.nyman/project/node_modules/karma-webpack/node_modules/async/lib/async.js:122:13
    at _each (/Users/jared.nyman/project/node_modules/karma-webpack/node_modules/async/lib/async.js:46:13)
    at async.each (/Users/jared.nyman/project/node_modules/karma-webpack/node_modules/async/lib/async.js:121:9)
    at _asyncMap (/Users/jared.nyman/project/node_modules/karma-webpack/node_modules/async/lib/async.js:245:13)
    at Object.map (/Users/jared.nyman/project/node_modules/karma-webpack/node_modules/async/lib/async.js:216:23)
    at Object.async.times (/Users/jared.nyman/project/node_modules/karma-webpack/node_modules/async/lib/async.js:1040:22)
    at Plugin.<anonymous> (/Users/jared.nyman/project/node_modules/karma-webpack/lib/karma-webpack.js:197:13)
    at Plugin.readFile (/Users/jared.nyman/project/node_modules/karma-webpack/lib/karma-webpack.js:239:5)
```

It looks like 0616dda489d07f6a9bc3def1778dcef601411821 introduced a subtle change:
`path.join(os.tmpdir(), '_karma_webpack_', idx, file.replace(/\\/g, '/')`

`idx` is no longer being coalesced into a string, which causes path.join to bomb

**Comment by grajagandev** [comment]
Would you be interested in software that automatically finds TypeErrors like this? I am building [Fuzz Stati0n](https://fuzzstati0n.com/?id=286) to do that (free for OSS) - please take a look and consider signing up for our newsletter to keep in touch.
